// ============================================================
// SHARED STRATEGY TYPES
// Single source of truth for frontend + backend
// ============================================================

/** Token candidate returned by the scan phase */
export interface TokenCandidate {
  id: string;
  symbol: string;
  name: string;
  address: string;
  chain: string;
  priceUsd: number;
  volume24h: number;
  liquidity: number;
  marketCap: number;
  priceChange24h: number;
  riskScore: number;
  phase: string | null;
  dnaRiskLevel: string;
  smartMoneyPct: number;
  botActivityPct: number;
  signalCount: number;
  tokenAgeCategory: 'NEW' | 'MEDIUM' | 'OLD';
}

/** Strategy configuration generated by the AI */
export interface StrategyConfig {
  id: string;
  name: string;
  category: string;
  icon: string;
  timeframe: string;
  tokenAgeCategory: string;
  riskTolerance: string;
  capitalAllocation: number;
  config: Record<string, unknown>;
}

/** Ranked backtest result from the ranking phase */
export interface RankResult {
  id: string;
  backtestId: string;
  strategyName: string;
  category: string;
  timeframe: string;
  tokenAgeCategory: string;
  riskTolerance: string;
  capitalAllocation: number;
  pnlPct: number;
  pnlUsd: number;
  sharpeRatio: number;
  winRate: number;
  maxDrawdownPct: number;
  profitFactor: number;
  totalTrades: number;
  avgHoldTimeMin: number;
  score: number;
  grade: string; // A+, A, B, C, D, F
  status: string;
  rank?: number;
}

/** Best strategy saved to Hall of Fame (matches AIBestStrategy Prisma model) */
export interface BestStrategy {
  id: string;
  strategyName: string;
  category: string;
  timeframe: string;
  tokenAgeCategory: string;
  riskTolerance: string;
  capitalAllocation: number;
  pnlPct: number;
  pnlUsd: number;
  sharpeRatio: number;
  winRate: number;
  maxDrawdownPct: number;
  profitFactor: number;
  totalTrades: number;
  avgHoldTimeMin: number;
  score: number;
  backtestId: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}
