"""
PPMT Local Storage - SQLite Persistence Layer

All data is stored locally in SQLite at ~/.ppmt/ppmt.db.
No cloud, no remote servers. 100% local.

Schema:
  - assets: Tracked symbols with classification
  - ohlcv: Candle data (open, high, low, close, volume, timestamp)
  - tries: Serialized PPMT Tries (JSON blobs per level)
  - engine_states: Engine metadata and statistics
  - signals: Historical signals generated by PPMT
"""

from __future__ import annotations

import json
import os
import sqlite3
from typing import Optional

import pandas as pd

from ppmt.core.trie import PPMTTrie


DB_DIR = os.path.expanduser("~/.ppmt")
DB_PATH = os.path.join(DB_DIR, "ppmt.db")


class PPMTStorage:
    """
    Local SQLite storage for PPMT data.

    All data stays on the user's machine. No cloud, no telemetry.
    The database stores OHLCV candles, serialized Tries, and
    engine state for persistence across sessions.

    Usage:
        storage = PPMTStorage()
        storage.save_ohlcv("BTC/USDT", "1h", df)
        df = storage.load_ohlcv("BTC/USDT", "1h")
        storage.close()
    """

    def __init__(self, db_path: Optional[str] = None):
        self.db_path = db_path or DB_PATH
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self.conn = sqlite3.connect(self.db_path)
        self.conn.execute("PRAGMA journal_mode=WAL")
        self.conn.execute("PRAGMA synchronous=NORMAL")
        self._create_tables()

    def _create_tables(self) -> None:
        """Create database tables if they don't exist."""
        cursor = self.conn.cursor()

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS assets (
                symbol TEXT PRIMARY KEY,
                asset_class TEXT NOT NULL DEFAULT 'default',
                weight_profile TEXT DEFAULT 'default',
                first_seen TEXT,
                last_updated TEXT,
                candle_count INTEGER DEFAULT 0
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS ohlcv (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL,
                timestamp INTEGER NOT NULL,
                open REAL NOT NULL,
                high REAL NOT NULL,
                low REAL NOT NULL,
                close REAL NOT NULL,
                volume REAL NOT NULL,
                UNIQUE(symbol, timeframe, timestamp)
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_ohlcv_symbol_tf
            ON ohlcv(symbol, timeframe, timestamp)
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS tries (
                symbol TEXT NOT NULL,
                level TEXT NOT NULL,
                data TEXT NOT NULL,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY(symbol, level)
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS engine_states (
                symbol TEXT PRIMARY KEY,
                data TEXT NOT NULL,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                signal_type TEXT NOT NULL,
                confidence REAL,
                quality_score REAL,
                sizing_multiplier REAL,
                entry_price REAL,
                sl_price REAL,
                tp_price REAL,
                expected_move_pct REAL,
                win_rate REAL,
                remaining_candles INTEGER,
                matched_pattern TEXT,
                predicted_path TEXT,
                timestamp REAL NOT NULL
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_symbol_ts
            ON signals(symbol, timestamp)
        """)

        self.conn.commit()

    # === Asset Management ===

    def register_asset(self, symbol: str, asset_class: str) -> None:
        """Register or update an asset in the database."""
        cursor = self.conn.cursor()
        cursor.execute(
            """INSERT INTO assets (symbol, asset_class, weight_profile, first_seen, last_updated)
               VALUES (?, ?, ?, datetime('now'), datetime('now'))
               ON CONFLICT(symbol) DO UPDATE SET
                   asset_class=excluded.asset_class,
                   last_updated=datetime('now')""",
            (symbol, asset_class, self._infer_weight_profile(asset_class)),
        )
        self.conn.commit()

    def get_assets(self) -> list[dict]:
        """Get all tracked assets with metadata."""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT a.symbol, a.asset_class, a.weight_profile,
                   a.first_seen, a.last_updated, a.candle_count
            FROM assets a
            ORDER BY a.symbol
        """)
        columns = ["symbol", "asset_class", "weight_profile", "first_seen", "last_updated", "candle_count"]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    @staticmethod
    def _infer_weight_profile(asset_class: str) -> str:
        """Map asset class to weight profile name."""
        profile_map = {
            "blue_chip": "blue_chip",
            "large_cap": "default",
            "mid_cap": "default",
            "defi": "default",
            "meme": "meme",
            "new_launch": "new_launch",
        }
        return profile_map.get(asset_class, "default")

    # === OHLCV Data ===

    def save_ohlcv(self, symbol: str, timeframe: str, df: pd.DataFrame) -> int:
        """
        Save OHLCV candle data to the database.

        Uses INSERT OR IGNORE to avoid duplicates.

        Args:
            symbol: Trading pair (e.g., 'BTC/USDT')
            timeframe: Candle timeframe (e.g., '1h')
            df: DataFrame with columns: open, high, low, close, volume
                Index should be DatetimeIndex or have a 'timestamp' column.

        Returns:
            Number of new candles inserted.
        """
        if df.empty:
            return 0

        # Prepare data
        rows = []
        for idx, row in df.iterrows():
            # Handle both DatetimeIndex and timestamp column
            if hasattr(idx, "value"):
                # pandas DatetimeIndex → unix timestamp in ms
                ts = int(idx.value / 1_000_000)
            elif "timestamp" in df.columns:
                ts = int(row["timestamp"])
            else:
                ts = int(idx)

            rows.append((
                symbol,
                timeframe,
                ts,
                float(row["open"]),
                float(row["high"]),
                float(row["low"]),
                float(row["close"]),
                float(row["volume"]),
            ))

        cursor = self.conn.cursor()
        cursor.executemany(
            """INSERT OR IGNORE INTO ohlcv
               (symbol, timeframe, timestamp, open, high, low, close, volume)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            rows,
        )
        inserted = cursor.rowcount

        # Update asset candle count
        cursor.execute(
            "UPDATE assets SET candle_count = (SELECT COUNT(*) FROM ohlcv WHERE symbol = ?), last_updated = datetime('now') WHERE symbol = ?",
            (symbol, symbol),
        )

        self.conn.commit()
        return inserted

    def load_ohlcv(self, symbol: str, timeframe: str) -> pd.DataFrame:
        """
        Load OHLCV data for a symbol and timeframe.

        Returns:
            DataFrame with DatetimeIndex and columns: open, high, low, close, volume
        """
        cursor = self.conn.cursor()
        cursor.execute(
            """SELECT timestamp, open, high, low, close, volume
               FROM ohlcv
               WHERE symbol = ? AND timeframe = ?
               ORDER BY timestamp ASC""",
            (symbol, timeframe),
        )
        rows = cursor.fetchall()

        if not rows:
            return pd.DataFrame()

        df = pd.DataFrame(rows, columns=["timestamp", "open", "high", "low", "close", "volume"])
        df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")
        df = df.set_index("timestamp")
        return df

    def get_candle_count(self, symbol: str, timeframe: str) -> int:
        """Get the number of stored candles for a symbol/timeframe."""
        cursor = self.conn.cursor()
        cursor.execute(
            "SELECT COUNT(*) FROM ohlcv WHERE symbol = ? AND timeframe = ?",
            (symbol, timeframe),
        )
        return cursor.fetchone()[0]

    def get_last_timestamp(self, symbol: str, timeframe: str) -> Optional[int]:
        """Get the last candle timestamp for incremental fetching."""
        cursor = self.conn.cursor()
        cursor.execute(
            "SELECT MAX(timestamp) FROM ohlcv WHERE symbol = ? AND timeframe = ?",
            (symbol, timeframe),
        )
        result = cursor.fetchone()[0]
        return result

    # === Trie Persistence ===

    def save_trie(self, symbol: str, level: str, trie: PPMTTrie) -> None:
        """
        Save a serialized Trie to the database.

        Args:
            symbol: Trading pair
            level: Trie level ('n1', 'n2', 'n3', 'n4')
            trie: PPMTTrie instance to serialize
        """
        data = json.dumps(trie.to_dict())
        cursor = self.conn.cursor()
        cursor.execute(
            """INSERT INTO tries (symbol, level, data, updated_at)
               VALUES (?, ?, ?, datetime('now'))
               ON CONFLICT(symbol, level) DO UPDATE SET
                   data=excluded.data,
                   updated_at=datetime('now')""",
            (symbol, level, data),
        )
        self.conn.commit()

    def load_trie(self, symbol: str, level: str) -> Optional[PPMTTrie]:
        """
        Load a serialized Trie from the database.

        Args:
            symbol: Trading pair
            level: Trie level ('n1', 'n2', 'n3', 'n4')

        Returns:
            PPMTTrie instance or None if not found.
        """
        cursor = self.conn.cursor()
        cursor.execute(
            "SELECT data FROM tries WHERE symbol = ? AND level = ?",
            (symbol, level),
        )
        row = cursor.fetchone()
        if row is None:
            return None

        try:
            data = json.loads(row[0])
            return PPMTTrie.from_dict(data)
        except (json.JSONDecodeError, KeyError):
            return None

    # === Engine State ===

    def save_engine_state(self, symbol: str, state: dict) -> None:
        """Save engine state (weights, stats) for persistence."""
        data = json.dumps(state, default=str)
        cursor = self.conn.cursor()
        cursor.execute(
            """INSERT INTO engine_states (symbol, data, updated_at)
               VALUES (?, ?, datetime('now'))
               ON CONFLICT(symbol) DO UPDATE SET
                   data=excluded.data,
                   updated_at=datetime('now')""",
            (symbol, data),
        )
        self.conn.commit()

    def load_engine_state(self, symbol: str) -> Optional[dict]:
        """Load engine state for a symbol."""
        cursor = self.conn.cursor()
        cursor.execute(
            "SELECT data FROM engine_states WHERE symbol = ?",
            (symbol,),
        )
        row = cursor.fetchone()
        if row is None:
            return None

        try:
            return json.loads(row[0])
        except json.JSONDecodeError:
            return None

    # === Signal History ===

    def save_signal(self, signal_dict: dict) -> None:
        """Save a signal to the history log."""
        cursor = self.conn.cursor()
        cursor.execute(
            """INSERT INTO signals
               (symbol, signal_type, confidence, quality_score, sizing_multiplier,
                entry_price, sl_price, tp_price, expected_move_pct, win_rate,
                remaining_candles, matched_pattern, predicted_path, timestamp)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                signal_dict.get("symbol", ""),
                signal_dict.get("signal_type", ""),
                signal_dict.get("confidence"),
                signal_dict.get("quality_score"),
                signal_dict.get("sizing_multiplier"),
                signal_dict.get("entry_price"),
                signal_dict.get("sl_price"),
                signal_dict.get("tp_price"),
                signal_dict.get("expected_move_pct"),
                signal_dict.get("win_rate"),
                signal_dict.get("remaining_candles"),
                json.dumps(signal_dict.get("matched_pattern", [])),
                json.dumps(signal_dict.get("predicted_path", [])),
                signal_dict.get("timestamp", 0),
            ),
        )
        self.conn.commit()

    def get_signals(
        self,
        symbol: str,
        limit: int = 100,
        signal_type: Optional[str] = None,
    ) -> list[dict]:
        """Get historical signals for a symbol."""
        cursor = self.conn.cursor()

        if signal_type:
            cursor.execute(
                """SELECT * FROM signals
                   WHERE symbol = ? AND signal_type = ?
                   ORDER BY timestamp DESC LIMIT ?""",
                (symbol, signal_type, limit),
            )
        else:
            cursor.execute(
                """SELECT * FROM signals
                   WHERE symbol = ?
                   ORDER BY timestamp DESC LIMIT ?""",
                (symbol, limit),
            )

        columns = [desc[0] for desc in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    # === Lifecycle ===

    def close(self) -> None:
        """Close the database connection."""
        if self.conn:
            self.conn.close()
            self.conn = None

    def __del__(self):
        self.close()
