"""
PPMT Local Storage - SQLite Persistence Layer

All data is stored locally in SQLite at ~/.ppmt/ppmt.db.
No cloud, no remote servers. 100% local.

Schema:
  - assets: Tracked symbols with classification
  - ohlcv: Candle data (open, high, low, close, volume, timestamp)
  - tries: Serialized PPMT Tries (JSON blobs per level)
  - engine_states: Engine metadata and statistics
  - signals: Historical signals generated by PPMT
  - trades: Closed trade history (v0.31.0)
"""

from __future__ import annotations

import json
import os
import sqlite3
import time
from typing import Optional

import pandas as pd

from ppmt.core.trie import PPMTTrie, RegimePartitionedTrie


# v0.40.3 FIX-1C: Special storage keys for cross-asset pools.
# N1 (universal) is shared across ALL symbols — saved under this pseudo-symbol.
# N2 (class-shared) is shared across all symbols in the same asset_class —
# saved under this prefix + asset_class name.
UNIVERSAL_POOL_KEY = "__UNIVERSAL__"
CLASS_POOL_PREFIX = "__CLASS_"


def class_pool_key(asset_class: str) -> str:
    """Build the storage key for an asset-class shared pool (N2)."""
    return f"{CLASS_POOL_PREFIX}{asset_class}"


def is_class_pool_key(symbol: str) -> bool:
    """True if the storage key refers to a class-shared pool."""
    return symbol.startswith(CLASS_POOL_PREFIX)


DB_DIR = os.path.expanduser("~/.ppmt")
DB_PATH = os.path.join(DB_DIR, "ppmt.db")


def compute_profit_factor(gross_profit: float, gross_loss: float, cap: float = 99.0) -> float:
    """Compute profit factor with a safe cap.

    v0.40.0: Shared formula used by both storage.get_trade_summary and
    server.validate_token. Previously two formulas existed:
      - server.py:1780 returned 0 when gross_loss == 0 (fails profitable tokens)
      - storage.py:744 floored gross_loss to 0.01, inflating PF to gross_profit/0.01
        (e.g. 100.0 when gross_profit=1.0)
    Both were wrong. Mathematically PF = ∞ when there are no losing trades.
    We cap at 99.0 so the value is JSON-safe and `pf_pass = PF > 0.8` succeeds
    for profitable-only tokens (as it should).

    Args:
        gross_profit: Sum of positive PnL (already positive).
        gross_loss:   Sum of |negative PnL| (already positive).
        cap:          Maximum returned value (default 99.0).

    Returns:
        PF in [0, cap]. Returns 0.0 when both gross_profit and gross_loss are 0
        (no trades at all). Returns cap when gross_profit > 0 and gross_loss == 0.
    """
    if gross_loss > 0:
        return min(gross_profit / gross_loss, cap)
    if gross_profit > 0:
        return cap
    return 0.0


class PPMTStorage:
    """
    Local SQLite storage for PPMT data.

    All data stays on the user's machine. No cloud, no telemetry.
    The database stores OHLCV candles, serialized Tries, and
    engine state for persistence across sessions.

    Usage:
        storage = PPMTStorage()
        storage.save_ohlcv("BTC/USDT", "1h", df)
        df = storage.load_ohlcv("BTC/USDT", "1h")
        storage.close()
    """

    def __init__(self, db_path: Optional[str] = None):
        self.db_path = db_path or DB_PATH
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self.conn = sqlite3.connect(self.db_path)
        self.conn.execute("PRAGMA journal_mode=WAL")
        self.conn.execute("PRAGMA synchronous=NORMAL")
        self._create_tables()

    def _reconnect(self) -> None:
        """v0.34.3: Re-open the connection after close() was called.

        Defensive helper used by validate_token() to recover from a closed
        storage instance (e.g. when a child component closed a shared storage
        by mistake). If conn is already open, this is a no-op.
        """
        if self.conn is not None:
            return
        self.conn = sqlite3.connect(self.db_path)
        self.conn.execute("PRAGMA journal_mode=WAL")
        self.conn.execute("PRAGMA synchronous=NORMAL")
        # _create_tables is idempotent (CREATE TABLE IF NOT EXISTS)
        self._create_tables()

    def _ensure_conn(self) -> "sqlite3.Connection":
        """v0.35.0: Lazy reconnect for ALL storage methods.

        Every read/write method calls `cursor = self._ensure_conn().cursor()`
        instead of `cursor = self._ensure_conn().cursor()`. If the connection was closed
        (e.g. by an early `storage.close()` in a pipeline), this transparently
        reopens it so the call succeeds instead of raising
        `'NoneType' object has no attribute 'cursor'`.

        This is the root-cause fix for the v0.34.x sweep errors where 50+ tokens
        per sweep were marked FAIL with the NoneType cursor error.
        """
        if self.conn is None:
            self._reconnect()
        return self.conn

    def _create_tables(self) -> None:
        """Create database tables if they don't exist."""
        cursor = self._ensure_conn().cursor()

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS assets (
                symbol TEXT PRIMARY KEY,
                asset_class TEXT NOT NULL DEFAULT 'default',
                weight_profile TEXT DEFAULT 'default',
                first_seen TEXT,
                last_updated TEXT,
                candle_count INTEGER DEFAULT 0
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS ohlcv (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL,
                timestamp INTEGER NOT NULL,
                open REAL NOT NULL,
                high REAL NOT NULL,
                low REAL NOT NULL,
                close REAL NOT NULL,
                volume REAL NOT NULL,
                UNIQUE(symbol, timeframe, timestamp)
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_ohlcv_symbol_tf
            ON ohlcv(symbol, timeframe, timestamp)
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS tries (
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL DEFAULT '',
                level TEXT NOT NULL,
                data TEXT NOT NULL,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY(symbol, timeframe, level)
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS engine_states (
                symbol TEXT PRIMARY KEY,
                data TEXT NOT NULL,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                signal_type TEXT NOT NULL,
                confidence REAL,
                quality_score REAL,
                sizing_multiplier REAL,
                entry_price REAL,
                sl_price REAL,
                tp_price REAL,
                expected_move_pct REAL,
                win_rate REAL,
                remaining_candles INTEGER,
                matched_pattern TEXT,
                predicted_path TEXT,
                timestamp REAL NOT NULL
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_symbol_ts
            ON signals(symbol, timestamp)
        """)

        # v0.31.0: Trade history table
        # v0.38.9: Added `source` column ('backtest' | 'live') so the dashboard
        # can show only live trades by default and hide backtest noise from
        # validation runs. Existing rows (pre-v0.38.9) get migrated to
        # source='backtest' since the vast majority of old data came from
        # validate_token() backtest runs, not from live/paper trading.
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS trades (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL DEFAULT '1h',
                direction TEXT NOT NULL,
                entry_price REAL NOT NULL,
                exit_price REAL,
                entry_time TEXT,
                exit_time TEXT,
                size REAL DEFAULT 0,
                pnl REAL DEFAULT 0,
                pnl_pct REAL DEFAULT 0,
                confidence REAL DEFAULT 0,
                exit_reason TEXT DEFAULT '',
                regime TEXT DEFAULT '',
                leverage INTEGER DEFAULT 1,
                kelly_fraction REAL DEFAULT 0,
                position_size_pct REAL DEFAULT 0,
                sl_price REAL,
                tp_price REAL,
                matched_pattern TEXT,
                node_id TEXT DEFAULT '',
                session_id TEXT DEFAULT '',
                source TEXT NOT NULL DEFAULT 'backtest',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # v0.38.9: Migration for existing DBs — add `source` column if missing.
        # SQLite doesn't support IF NOT EXISTS on ALTER TABLE, so we check
        # pragma_table_info first. Default 'backtest' assumes pre-v0.38.9 data
        # came from validation runs (which was the case for the user reporting
        # 434 fake BTC trades at backtest prices polluting the live view).
        cursor.execute("PRAGMA table_info(trades)")
        existing_cols = {row[1] for row in cursor.fetchall()}
        if 'source' not in existing_cols:
            cursor.execute(
                "ALTER TABLE trades ADD COLUMN source TEXT NOT NULL DEFAULT 'backtest'"
            )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_trades_source ON trades(source)"
            )
        else:
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_trades_source ON trades(source)"
            )

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_trades_symbol
            ON trades(symbol, timeframe, created_at DESC)
        """)

        # v0.31.0: Validation results table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS validations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL DEFAULT '1h',
                verdict TEXT NOT NULL,
                win_rate REAL DEFAULT 0,
                profit_factor REAL DEFAULT 0,
                risk_of_ruin REAL DEFAULT 0,
                p95_drawdown REAL DEFAULT 0,
                total_trades INTEGER DEFAULT 0,
                backtest_pnl_pct REAL DEFAULT 0,
                mc_probability_profit REAL DEFAULT 0,
                mc_verdict TEXT DEFAULT '',
                details TEXT DEFAULT '{}',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_validations_symbol
            ON validations(symbol, timeframe, created_at DESC)
        """)

        self._ensure_conn().commit()

    # === Asset Management ===

    def register_asset(self, symbol: str, asset_class: str) -> None:
        """Register or update an asset in the database."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO assets (symbol, asset_class, weight_profile, first_seen, last_updated)
               VALUES (?, ?, ?, datetime('now'), datetime('now'))
               ON CONFLICT(symbol) DO UPDATE SET
                   asset_class=excluded.asset_class,
                   last_updated=datetime('now')""",
            (symbol, asset_class, self._infer_weight_profile(asset_class)),
        )
        self._ensure_conn().commit()

    def get_assets(self) -> list[dict]:
        """Get all tracked assets with metadata."""
        cursor = self._ensure_conn().cursor()
        cursor.execute("""
            SELECT a.symbol, a.asset_class, a.weight_profile,
                   a.first_seen, a.last_updated, a.candle_count
            FROM assets a
            ORDER BY a.symbol
        """)
        columns = ["symbol", "asset_class", "weight_profile", "first_seen", "last_updated", "candle_count"]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    @staticmethod
    def _infer_weight_profile(asset_class: str) -> str:
        """Map asset class to weight profile name."""
        profile_map = {
            "blue_chip": "blue_chip",
            "large_cap": "default",
            "mid_cap": "default",
            "defi": "default",
            "meme": "meme",
            "new_launch": "new_launch",
        }
        return profile_map.get(asset_class, "default")

    # === OHLCV Data ===

    def save_ohlcv(self, symbol: str, timeframe: str, df: pd.DataFrame) -> int:
        """
        Save OHLCV candle data to the database.

        Uses INSERT OR IGNORE to avoid duplicates.

        Args:
            symbol: Trading pair (e.g., 'BTC/USDT')
            timeframe: Candle timeframe (e.g., '1h')
            df: DataFrame with columns: open, high, low, close, volume
                Index should be DatetimeIndex or have a 'timestamp' column.

        Returns:
            Number of new candles inserted.
        """
        if df.empty:
            return 0

        # Prepare data
        rows = []
        for idx, row in df.iterrows():
            # Handle both DatetimeIndex and timestamp column
            if hasattr(idx, "value"):
                # pandas DatetimeIndex → unix timestamp in ms
                ts = int(idx.value / 1_000_000)
            elif "timestamp" in df.columns:
                ts = int(row["timestamp"])
            else:
                ts = int(idx)

            rows.append((
                symbol,
                timeframe,
                ts,
                float(row["open"]),
                float(row["high"]),
                float(row["low"]),
                float(row["close"]),
                float(row["volume"]),
            ))

        cursor = self._ensure_conn().cursor()
        cursor.executemany(
            """INSERT OR IGNORE INTO ohlcv
               (symbol, timeframe, timestamp, open, high, low, close, volume)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            rows,
        )
        inserted = cursor.rowcount

        # Update asset candle count
        cursor.execute(
            "UPDATE assets SET candle_count = (SELECT COUNT(*) FROM ohlcv WHERE symbol = ?), last_updated = datetime('now') WHERE symbol = ?",
            (symbol, symbol),
        )

        self._ensure_conn().commit()
        return inserted

    def load_ohlcv(self, symbol: str, timeframe: str) -> pd.DataFrame:
        """
        Load OHLCV data for a symbol and timeframe.

        Returns:
            DataFrame with DatetimeIndex and columns: open, high, low, close, volume
        """
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """SELECT timestamp, open, high, low, close, volume
               FROM ohlcv
               WHERE symbol = ? AND timeframe = ?
               ORDER BY timestamp ASC""",
            (symbol, timeframe),
        )
        rows = cursor.fetchall()

        if not rows:
            return pd.DataFrame()

        df = pd.DataFrame(rows, columns=["timestamp", "open", "high", "low", "close", "volume"])
        df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")
        df = df.set_index("timestamp")
        return df

    def get_candle_count(self, symbol: str, timeframe: str) -> int:
        """Get the number of stored candles for a symbol/timeframe."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            "SELECT COUNT(*) FROM ohlcv WHERE symbol = ? AND timeframe = ?",
            (symbol, timeframe),
        )
        return cursor.fetchone()[0]

    def get_last_timestamp(self, symbol: str, timeframe: str) -> Optional[int]:
        """Get the last candle timestamp for incremental fetching."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            "SELECT MAX(timestamp) FROM ohlcv WHERE symbol = ? AND timeframe = ?",
            (symbol, timeframe),
        )
        result = cursor.fetchone()[0]
        return result

    # === Trie Persistence ===

    def save_trie(self, symbol: str, level: str, trie: PPMTTrie, timeframe: str = "") -> None:
        """
        Save a serialized Trie to the database.

        FASE 1 Tarea 1.3 (dual-sax compatibility): Trie nodes may now have
        string keys containing '|' (e.g., 'a|x' for dual price+volume symbols).
        These serialize naturally via JSON — no special handling needed.
        Backwards-compatible: old tries with single-symbol keys ('a', 'b', ...)
        continue to load correctly.

        v0.53.0: Added `timeframe` parameter. Tries are now keyed by
        (symbol, timeframe, level) so that 1m, 5m, and 15m tries can
        coexist in the same database without overwriting each other.
        Default "" preserves backward compatibility for callers that
        don't pass timeframe.

        Args:
            symbol: Trading pair
            level: Trie level ('n1', 'n2', 'n3', 'n4')
            trie: PPMTTrie instance to serialize
            timeframe: Timeframe identifier ('1m', '5m', '15m'). Default "".
        """
        data = json.dumps(trie.to_dict())
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO tries (symbol, timeframe, level, data, updated_at)
               VALUES (?, ?, ?, ?, datetime('now'))
               ON CONFLICT(symbol, timeframe, level) DO UPDATE SET
                   data=excluded.data,
                   updated_at=datetime('now')""",
            (symbol, timeframe, level, data),
        )
        self._ensure_conn().commit()

    def load_trie(self, symbol: str, level: str, timeframe: str = "") -> Optional[PPMTTrie]:
        """
        Load a serialized Trie from the database.

        v0.40.3 FIX-1C: Polymorphic trie loading. The serialized payload may
        be a plain PPMTTrie (keys: 'symbol', 'children', 'depth', 'metadata')
        OR a RegimePartitionedTrie (keys: 'type', 'name', 'sub_tries', ...).
        We dispatch on the `"type"` marker so N4 survives save/load cycles.
        Before this fix, N4 (RegimePartitionedTrie) was silently degraded to
        an empty PPMTTrie on every restart — see
        docs/AUDIT_TRAZABILIDAD_CAPAS_1_2_3.md H2 (persistence bug).

        v0.53.0: Added `timeframe` parameter for per-timeframe trie lookup.
        Tries are now keyed by (symbol, timeframe, level). Default "" for
        backward compatibility.

        Args:
            symbol: Trading pair (or special pool key: __UNIVERSAL__, __CLASS_*__)
            level: Trie level ('n1', 'n2', 'n3', 'n4')
            timeframe: Timeframe identifier ('1m', '5m', '15m'). Default "".

        Returns:
            PPMTTrie / RegimePartitionedTrie instance or None if not found.
        """
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            "SELECT data FROM tries WHERE symbol = ? AND timeframe = ? AND level = ?",
            (symbol, timeframe, level),
        )
        row = cursor.fetchone()
        if row is None:
            return None

        try:
            data = json.loads(row[0])
            # FIX-1C: dispatch on type marker
            if isinstance(data, dict) and data.get("type") == "regime_partitioned":
                return RegimePartitionedTrie.from_dict(data)
            return PPMTTrie.from_dict(data)
        except (json.JSONDecodeError, KeyError):
            return None

    def load_all_tries(
        self,
        symbol: str,
        asset_class: Optional[str] = None,
        timeframe: str = "",
    ) -> dict[str, Optional[PPMTTrie]]:
        """
        Load all 4 trie levels for a symbol.

        v0.10.0: Convenience method for PaperTrader 4-level integration.
        v0.40.3 FIX-1B: When `asset_class` is provided, N1 is loaded from the
        universal pool (`__UNIVERSAL__`, shared across all symbols) and N2 is
        loaded from the class-shared pool (`__CLASS_<asset_class>__`, shared
        across all symbols in the same class). N3 and N4 remain per-symbol.
        This matches the original V3 design (PPMT_Technical_Document_V3.pdf
        §3.1-3.4) where N1 is the universal safety-net and N2 is the
        competitive-advantage class pool.

        v0.53.0: Added `timeframe` parameter for per-timeframe trie lookup.
        All levels (N1-N4) are loaded with the same timeframe key.

        When `asset_class` is None (backwards compatibility), N1/N2 are loaded
        from the symbol's own storage key — the v0.40.2 behavior. This is
        kept so existing callers don't break, but new callers should always
        pass asset_class.

        Args:
            symbol: Trading pair
            asset_class: Optional asset class ('blue_chip', 'large_cap',
                'mid_cap', 'defi', 'meme', 'new_launch'). When provided,
                N1/N2 load from shared pools.
            timeframe: Timeframe identifier ('1m', '5m', '15m'). Default "".

        Returns:
            Dict with keys 'n1', 'n2', 'n3', 'n4' mapping to PPMTTrie or None.
        """
        if asset_class is not None:
            # FIX-1B: shared pools for N1 (universal) and N2 (class)
            n1_symbol = UNIVERSAL_POOL_KEY
            n2_symbol = class_pool_key(asset_class)
        else:
            # Backwards-compat: per-symbol N1/N2 (pre-FIX-1B behavior)
            n1_symbol = symbol
            n2_symbol = symbol

        return {
            "n1": self.load_trie(n1_symbol, "n1", timeframe=timeframe),
            "n2": self.load_trie(n2_symbol, "n2", timeframe=timeframe),
            "n3": self.load_trie(symbol, "n3", timeframe=timeframe),
            "n4": self.load_trie(symbol, "n4", timeframe=timeframe),
        }

    def add_observation_to_universal_n1(
        self,
        symbols: list[str],
        move_pct: float = 0.0,
        drawdown_pct: float = 0.0,
        favorable_pct: float = 0.0,
        duration: int = 0,
        won: bool = False,
        next_symbol: Optional[str] = None,
        regime: Optional[str] = None,
        regime_confidence: Optional[float] = None,
        timeframe: str = "",
    ) -> None:
        """
        v0.40.3 FIX-1B: Add a single observation to the universal N1 pool.

        The universal pool is shared across ALL symbols (storage key
        `__UNIVERSAL__`). Used by PPMT.build() to contribute each new
        observation to the cross-asset safety net so that even brand-new
        symbols with no own history have N1 patterns to match against.

        v0.53.0: Added `timeframe` parameter for per-timeframe pool support.

        Idempotent: if the pattern already exists, metadata is updated
        incrementally (same as PPMTTrie.insert_with_observations).
        """
        trie = self.load_trie(UNIVERSAL_POOL_KEY, "n1", timeframe=timeframe) or PPMTTrie(name="universal")
        trie.insert_with_observations(
            symbols=symbols,
            move_pct=move_pct,
            drawdown_pct=drawdown_pct,
            favorable_pct=favorable_pct,
            duration=duration,
            won=won,
            next_symbol=next_symbol,
            regime=regime,
            regime_confidence=regime_confidence,
        )
        self.save_trie(UNIVERSAL_POOL_KEY, "n1", trie, timeframe=timeframe)

    def add_observation_to_class_n2(
        self,
        asset_class: str,
        symbols: list[str],
        move_pct: float = 0.0,
        drawdown_pct: float = 0.0,
        favorable_pct: float = 0.0,
        duration: int = 0,
        won: bool = False,
        next_symbol: Optional[str] = None,
        regime: Optional[str] = None,
        regime_confidence: Optional[float] = None,
        timeframe: str = "",
    ) -> None:
        """
        v0.40.3 FIX-1B: Add a single observation to the class-shared N2 pool.

        The class pool is shared across all symbols in the same asset_class
        (storage key `__CLASS_<asset_class>__`). Used by PPMT.build() to
        contribute each new observation so the "competitive advantage" of
        the V3 design (patterns transfer between same-class assets —
        BTC ↔ ETH for blue_chip, PEPE ↔ WIF for meme) is finally realized.

        v0.53.0: Added `timeframe` parameter for per-timeframe pool support.

        Idempotent: if the pattern already exists, metadata is updated
        incrementally.
        """
        pool_key = class_pool_key(asset_class)
        trie = self.load_trie(pool_key, "n2", timeframe=timeframe) or PPMTTrie(name=f"class:{asset_class}")
        trie.insert_with_observations(
            symbols=symbols,
            move_pct=move_pct,
            drawdown_pct=drawdown_pct,
            favorable_pct=favorable_pct,
            duration=duration,
            won=won,
            next_symbol=next_symbol,
            regime=regime,
            regime_confidence=regime_confidence,
        )
        self.save_trie(pool_key, "n2", trie, timeframe=timeframe)

    # === Engine State ===

    def save_engine_state(self, symbol: str, state: dict) -> None:
        """Save engine state (weights, stats) for persistence."""
        data = json.dumps(state, default=str)
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO engine_states (symbol, data, updated_at)
               VALUES (?, ?, datetime('now'))
               ON CONFLICT(symbol) DO UPDATE SET
                   data=excluded.data,
                   updated_at=datetime('now')""",
            (symbol, data),
        )
        self._ensure_conn().commit()

    def load_engine_state(self, symbol: str) -> Optional[dict]:
        """Load engine state for a symbol."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            "SELECT data FROM engine_states WHERE symbol = ?",
            (symbol,),
        )
        row = cursor.fetchone()
        if row is None:
            return None

        try:
            return json.loads(row[0])
        except json.JSONDecodeError:
            return None

    # === Signal History ===

    def save_signal(self, signal_dict: dict) -> None:
        """Save a signal to the history log."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO signals
               (symbol, signal_type, confidence, quality_score, sizing_multiplier,
                entry_price, sl_price, tp_price, expected_move_pct, win_rate,
                remaining_candles, matched_pattern, predicted_path, timestamp)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                signal_dict.get("symbol", ""),
                signal_dict.get("signal_type", ""),
                signal_dict.get("confidence"),
                signal_dict.get("quality_score"),
                signal_dict.get("sizing_multiplier"),
                signal_dict.get("entry_price"),
                signal_dict.get("sl_price"),
                signal_dict.get("tp_price"),
                signal_dict.get("expected_move_pct"),
                signal_dict.get("win_rate"),
                signal_dict.get("remaining_candles"),
                json.dumps(signal_dict.get("matched_pattern", [])),
                json.dumps(signal_dict.get("predicted_path", [])),
                signal_dict.get("timestamp", 0),
            ),
        )
        self._ensure_conn().commit()

    def get_signals(
        self,
        symbol: str,
        limit: int = 100,
        signal_type: Optional[str] = None,
    ) -> list[dict]:
        """Get historical signals for a symbol."""
        cursor = self._ensure_conn().cursor()

        if signal_type:
            cursor.execute(
                """SELECT * FROM signals
                   WHERE symbol = ? AND signal_type = ?
                   ORDER BY timestamp DESC LIMIT ?""",
                (symbol, signal_type, limit),
            )
        else:
            cursor.execute(
                """SELECT * FROM signals
                   WHERE symbol = ?
                   ORDER BY timestamp DESC LIMIT ?""",
                (symbol, limit),
            )

        columns = [desc[0] for desc in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    # === Lifecycle ===

    def close(self) -> None:
        """Close the database connection."""
        if self.conn:
            self.conn.close()
            self.conn = None

    def __del__(self):
        self.close()

    # === Trade History (v0.31.0) ===

    def save_trade(self, trade_dict: dict) -> int:
        """Save a closed trade to the history log.

        v0.38.9: Added deduplication + source field. If a row with the same
        (symbol, entry_time, exit_time, entry_price, exit_price, source)
        already exists, the insert is skipped. This prevents the same backtest
        trade from being saved multiple times when a token is re-validated in
        successive sweeps (the original cause of the "16 trades shown but only
        8 unique" bug).

        Args:
            trade_dict: Dict with trade fields (symbol, direction, entry_price,
                etc.). Optional `source` field ('live' | 'backtest', default
                'backtest' for backward compat with validation callers).

        Returns:
            Row ID of the inserted trade (or the existing row ID if dedup hit).
        """
        cursor = self._ensure_conn().cursor()
        source = trade_dict.get("source", "backtest")
        symbol = trade_dict.get("symbol", "")
        entry_time = trade_dict.get("entry_time", "")
        exit_time = trade_dict.get("exit_time", "")
        entry_price = trade_dict.get("entry_price", 0)
        exit_price = trade_dict.get("exit_price", 0)

        # v0.38.9: Dedup — skip if same trade already saved. Match on the
        # immutable trade signature (symbol + times + prices + source). PnL
        # is excluded since it's derived from prices.
        cursor.execute(
            """SELECT id FROM trades
               WHERE symbol = ? AND entry_time = ? AND exit_time = ?
                 AND entry_price = ? AND exit_price = ? AND source = ?
               LIMIT 1""",
            (symbol, entry_time, exit_time, entry_price, exit_price, source),
        )
        existing = cursor.fetchone()
        if existing:
            return existing[0]

        cursor.execute(
            """INSERT INTO trades
               (symbol, timeframe, direction, entry_price, exit_price,
                entry_time, exit_time, size, pnl, pnl_pct,
                confidence, exit_reason, regime, leverage,
                kelly_fraction, position_size_pct, sl_price, tp_price,
                matched_pattern, node_id, session_id, source)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                symbol,
                trade_dict.get("timeframe", "1h"),
                trade_dict.get("direction", ""),
                entry_price,
                exit_price,
                entry_time,
                exit_time,
                trade_dict.get("size", 0),
                trade_dict.get("pnl", 0),
                trade_dict.get("pnl_pct", 0),
                trade_dict.get("confidence", 0),
                trade_dict.get("exit_reason", ""),
                trade_dict.get("regime", ""),
                trade_dict.get("leverage", 1),
                trade_dict.get("kelly_fraction", 0),
                trade_dict.get("position_size_pct", 0),
                trade_dict.get("sl_price"),
                trade_dict.get("tp_price"),
                json.dumps(trade_dict.get("matched_pattern", [])),
                trade_dict.get("node_id", ""),
                trade_dict.get("session_id", ""),
                source,
            ),
        )
        self._ensure_conn().commit()
        return cursor.lastrowid

    def get_trades(
        self,
        symbol: Optional[str] = None,
        timeframe: Optional[str] = None,
        limit: int = 100,
        node_id: Optional[str] = None,
        source: Optional[str] = None,
    ) -> list[dict]:
        """Get closed trade history, most recent first.

        v0.38.9: Added `source` filter. Pass 'live' to see only live/paper
        trades, 'backtest' for validation runs, or None for all.

        Args:
            symbol: Filter by symbol (optional)
            timeframe: Filter by timeframe (optional)
            limit: Max trades to return
            node_id: Filter by node ID (optional)
            source: Filter by source ('live' | 'backtest' | None for all)
        """
        cursor = self._ensure_conn().cursor()
        conditions = []
        params = []

        if symbol:
            conditions.append("symbol = ?")
            params.append(symbol)
        if timeframe:
            conditions.append("timeframe = ?")
            params.append(timeframe)
        if node_id:
            conditions.append("node_id = ?")
            params.append(node_id)
        if source:
            conditions.append("source = ?")
            params.append(source)

        where = f"WHERE {' AND '.join(conditions)}" if conditions else ""
        params.append(limit)

        cursor.execute(
            f"""SELECT * FROM trades {where}
                ORDER BY created_at DESC LIMIT ?""",
            params,
        )
        columns = [desc[0] for desc in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    def get_trade_summary(
        self,
        symbol: Optional[str] = None,
        source: Optional[str] = None,
    ) -> dict:
        """Get aggregate trade statistics.

        v0.38.9: Added `source` filter (default None = all sources).
        Pass 'live' to compute stats only on live/paper trades.

        Returns total trades, win rate, P&L, etc.
        """
        cursor = self._ensure_conn().cursor()
        conditions = []
        params = []
        if symbol:
            conditions.append("symbol = ?")
            params.append(symbol)
        if source:
            conditions.append("source = ?")
            params.append(source)
        condition = f"WHERE {' AND '.join(conditions)}" if conditions else ""

        cursor.execute(
            f"""SELECT COUNT(*) as total_trades,
                   SUM(CASE WHEN pnl_pct > 0 THEN 1 ELSE 0 END) as winning_trades,
                   SUM(CASE WHEN pnl_pct <= 0 THEN 1 ELSE 0 END) as losing_trades,
                   COALESCE(SUM(pnl), 0) as total_pnl,
                   COALESCE(AVG(pnl_pct), 0) as avg_pnl_pct,
                   COALESCE(MAX(pnl_pct), 0) as best_trade_pct,
                   COALESCE(MIN(pnl_pct), 0) as worst_trade_pct,
                   COALESCE(SUM(CASE WHEN pnl_pct > 0 THEN pnl_pct ELSE 0 END), 0) as gross_profit,
                   COALESCE(SUM(CASE WHEN pnl_pct < 0 THEN ABS(pnl_pct) ELSE 0 END), 0) as gross_loss
               FROM trades {condition}""",
            params,
        )
        row = cursor.fetchone()
        if row is None:
            return {"total_trades": 0}

        total = row[0] or 0
        wins = row[1] or 0
        gross_profit = row[7] or 0
        gross_loss = row[8] or 0  # v0.40.0: don't floor to 0.01 anymore

        return {
            "total_trades": total,
            "winning_trades": wins,
            "losing_trades": row[2] or 0,
            "win_rate": wins / total if total > 0 else 0,
            "total_pnl": row[3] or 0,
            "avg_pnl_pct": row[4] or 0,
            "best_trade_pct": row[5] or 0,
            "worst_trade_pct": row[6] or 0,
            "profit_factor": compute_profit_factor(gross_profit, gross_loss),
        }

    def clear_trades(
        self,
        symbol: Optional[str] = None,
        older_than_days: int = 0,
        source: Optional[str] = None,
    ) -> int:
        """Delete trade history rows.

        v0.37.0: Added so users can clear stale/backtest trades that pollute
        the dashboard's Trade History panel (e.g. 434 fake BTC trades at
        $38,452 from a previous backtest, shown while trading XLM/OP/ICP).
        v0.38.9: Added `source` filter — pass 'backtest' to clear only
        backtest data while preserving live trades, or 'live' for the
        reverse.

        Args:
            symbol: If provided, only delete trades for this symbol.
                    If None, delete ALL trades (use with caution).
            older_than_days: If >0, only delete trades older than N days
                             (based on created_at). 0 = delete all matching.
            source: If provided, only delete trades with this source
                    ('live' | 'backtest'). None = delete all sources.

        Returns:
            Number of rows deleted.
        """
        cursor = self._ensure_conn().cursor()
        conditions = []
        params: list = []

        if symbol:
            conditions.append("symbol = ?")
            params.append(symbol)
        if older_than_days > 0:
            conditions.append(
                "created_at < datetime('now', ?)"
            )
            params.append(f"-{older_than_days} days")
        if source:
            conditions.append("source = ?")
            params.append(source)

        where = f"WHERE {' AND '.join(conditions)}" if conditions else ""

        cursor.execute(f"DELETE FROM trades {where}", params)
        deleted = cursor.rowcount
        self._ensure_conn().commit()
        return deleted

    def clear_signals(self, symbol: Optional[str] = None, older_than_days: int = 0) -> int:
        """Delete signal history rows.

        v0.37.0: Companion to clear_trades() for clearing stale signals.
        v0.39.1 FIX: Previously used `created_at` which DOES NOT EXIST
        on the signals table (only on trades/validations). The DELETE
        silently failed with "no such column: created_at" caught by
        the outer try/except in callers → user saw signals never being
        cleared. Now uses `timestamp` (epoch seconds, REAL) with the
        equivalent datetime cutoff.

        Args:
            symbol: If provided, only delete signals for this symbol.
            older_than_days: If >0, only delete signals older than N days.

        Returns:
            Number of rows deleted.
        """
        cursor = self._ensure_conn().cursor()
        conditions = []
        params: list = []

        if symbol:
            conditions.append("symbol = ?")
            params.append(symbol)
        if older_than_days > 0:
            # signals.timestamp is REAL (epoch seconds).
            # Compute the cutoff as epoch and compare numerically.
            cutoff_epoch = (time.time()) - (older_than_days * 86400.0)
            conditions.append("timestamp < ?")
            params.append(cutoff_epoch)

        where = f"WHERE {' AND '.join(conditions)}" if conditions else ""

        cursor.execute(f"DELETE FROM signals {where}", params)
        deleted = cursor.rowcount
        self._ensure_conn().commit()
        return deleted

    # === Validation Results (v0.31.0) ===

    def save_validation(self, val_dict: dict) -> int:
        """Save a validation result.

        v0.40.0: UPSERT on (symbol, timeframe) — previously a plain INSERT
        which produced duplicated rows when _run_one_token re-validated
        INSUFFICIENT_DATA tokens. Now we delete older rows for the same
        (symbol, timeframe) before inserting, keeping only the latest.
        """
        cursor = self._ensure_conn().cursor()
        symbol = val_dict.get("symbol", "")
        timeframe = val_dict.get("timeframe", "1h")
        # v0.40.0: Delete older rows for same (symbol, timeframe) BEFORE insert.
        # Simpler than ON CONFLICT because the existing table has no UNIQUE
        # constraint; this avoids a migration.
        cursor.execute(
            "DELETE FROM validations WHERE symbol = ? AND timeframe = ?",
            (symbol, timeframe),
        )
        cursor.execute(
            """INSERT INTO validations
               (symbol, timeframe, verdict, win_rate, profit_factor,
                risk_of_ruin, p95_drawdown, total_trades, backtest_pnl_pct,
                mc_probability_profit, mc_verdict, details)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                symbol,
                timeframe,
                val_dict.get("verdict", "UNKNOWN"),
                val_dict.get("win_rate", 0),
                val_dict.get("profit_factor", 0),
                val_dict.get("risk_of_ruin", 0),
                val_dict.get("p95_drawdown", 0),
                val_dict.get("total_trades", 0),
                val_dict.get("backtest_pnl_pct", 0),
                val_dict.get("mc_probability_profit", 0),
                val_dict.get("mc_verdict", ""),
                json.dumps(val_dict.get("details", {})),
            ),
        )
        self._ensure_conn().commit()
        return cursor.lastrowid

    def get_latest_validation(self, symbol: str, timeframe: str = "1h") -> Optional[dict]:
        """Get the most recent validation result for a symbol/timeframe."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """SELECT * FROM validations
               WHERE symbol = ? AND timeframe = ?
               ORDER BY created_at DESC LIMIT 1""",
            (symbol, timeframe),
        )
        row = cursor.fetchone()
        if row is None:
            return None
        columns = [desc[0] for desc in cursor.description]
        return dict(zip(columns, row))

    # === TokenProfile Persistence ===

    def save_token_profile(self, symbol: str, timeframe: str, profile_dict: dict) -> None:
        """
        Save a calibrated TokenProfile to the database.

        v0.11.0: Persists calibrated α/W and all profile parameters so the next
        run doesn't need to re-calibrate from scratch. The profile is stored
        in the engine_states table with a compound key 'symbol:timeframe:profile'.

        Args:
            symbol: Trading pair (e.g., 'BTC/USDT')
            timeframe: Candle timeframe (e.g., '1h')
            profile_dict: Serialized TokenProfile (from TokenProfile.to_dict())
        """
        key = f"{symbol}:{timeframe}:profile"
        data = json.dumps(profile_dict, default=str)
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO engine_states (symbol, data, updated_at)
               VALUES (?, ?, datetime('now'))
               ON CONFLICT(symbol) DO UPDATE SET
                   data=excluded.data,
                   updated_at=datetime('now')""",
            (key, data),
        )
        self._ensure_conn().commit()

    def load_token_profile(self, symbol: str, timeframe: str) -> Optional[dict]:
        """
        Load a saved TokenProfile from the database.

        v0.11.0: Returns the serialized profile dict if a calibrated profile
        was previously saved, or None if no profile exists for this
        symbol+timeframe combination. The caller can use this to skip
        calibration and go straight to trading.

        Args:
            symbol: Trading pair (e.g., 'BTC/USDT')
            timeframe: Candle timeframe (e.g., '1h')

        Returns:
            Dict with TokenProfile fields, or None if not found.
        """
        key = f"{symbol}:{timeframe}:profile"
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            "SELECT data FROM engine_states WHERE symbol = ?",
            (key,),
        )
        row = cursor.fetchone()
        if row is None:
            return None

        try:
            return json.loads(row[0])
        except json.JSONDecodeError:
            return None
