"""
PPMT Local Storage - SQLite Persistence Layer

All data is stored locally in SQLite at ~/.ppmt/ppmt.db.
No cloud, no remote servers. 100% local.

Schema:
  - assets: Tracked symbols with classification
  - ohlcv: Candle data (open, high, low, close, volume, timestamp)
  - tries: Serialized PPMT Tries (JSON blobs per level)
  - engine_states: Engine metadata and statistics
  - signals: Historical signals generated by PPMT
  - trades: Closed trade history (v0.31.0)
"""

from __future__ import annotations

import json
import os
import sqlite3
from typing import Optional

import pandas as pd

from ppmt.core.trie import PPMTTrie


DB_DIR = os.path.expanduser("~/.ppmt")
DB_PATH = os.path.join(DB_DIR, "ppmt.db")


class PPMTStorage:
    """
    Local SQLite storage for PPMT data.

    All data stays on the user's machine. No cloud, no telemetry.
    The database stores OHLCV candles, serialized Tries, and
    engine state for persistence across sessions.

    Usage:
        storage = PPMTStorage()
        storage.save_ohlcv("BTC/USDT", "1h", df)
        df = storage.load_ohlcv("BTC/USDT", "1h")
        storage.close()
    """

    def __init__(self, db_path: Optional[str] = None):
        self.db_path = db_path or DB_PATH
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self.conn = sqlite3.connect(self.db_path)
        self.conn.execute("PRAGMA journal_mode=WAL")
        self.conn.execute("PRAGMA synchronous=NORMAL")
        self._create_tables()

    def _reconnect(self) -> None:
        """v0.34.3: Re-open the connection after close() was called.

        Defensive helper used by validate_token() to recover from a closed
        storage instance (e.g. when a child component closed a shared storage
        by mistake). If conn is already open, this is a no-op.
        """
        if self.conn is not None:
            return
        self.conn = sqlite3.connect(self.db_path)
        self.conn.execute("PRAGMA journal_mode=WAL")
        self.conn.execute("PRAGMA synchronous=NORMAL")
        # _create_tables is idempotent (CREATE TABLE IF NOT EXISTS)
        self._create_tables()

    def _ensure_conn(self) -> "sqlite3.Connection":
        """v0.35.0: Lazy reconnect for ALL storage methods.

        Every read/write method calls `cursor = self._ensure_conn().cursor()`
        instead of `cursor = self._ensure_conn().cursor()`. If the connection was closed
        (e.g. by an early `storage.close()` in a pipeline), this transparently
        reopens it so the call succeeds instead of raising
        `'NoneType' object has no attribute 'cursor'`.

        This is the root-cause fix for the v0.34.x sweep errors where 50+ tokens
        per sweep were marked FAIL with the NoneType cursor error.
        """
        if self.conn is None:
            self._reconnect()
        return self.conn

    def _create_tables(self) -> None:
        """Create database tables if they don't exist."""
        cursor = self._ensure_conn().cursor()

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS assets (
                symbol TEXT PRIMARY KEY,
                asset_class TEXT NOT NULL DEFAULT 'default',
                weight_profile TEXT DEFAULT 'default',
                first_seen TEXT,
                last_updated TEXT,
                candle_count INTEGER DEFAULT 0
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS ohlcv (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL,
                timestamp INTEGER NOT NULL,
                open REAL NOT NULL,
                high REAL NOT NULL,
                low REAL NOT NULL,
                close REAL NOT NULL,
                volume REAL NOT NULL,
                UNIQUE(symbol, timeframe, timestamp)
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_ohlcv_symbol_tf
            ON ohlcv(symbol, timeframe, timestamp)
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS tries (
                symbol TEXT NOT NULL,
                level TEXT NOT NULL,
                data TEXT NOT NULL,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY(symbol, level)
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS engine_states (
                symbol TEXT PRIMARY KEY,
                data TEXT NOT NULL,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                signal_type TEXT NOT NULL,
                confidence REAL,
                quality_score REAL,
                sizing_multiplier REAL,
                entry_price REAL,
                sl_price REAL,
                tp_price REAL,
                expected_move_pct REAL,
                win_rate REAL,
                remaining_candles INTEGER,
                matched_pattern TEXT,
                predicted_path TEXT,
                timestamp REAL NOT NULL
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_symbol_ts
            ON signals(symbol, timestamp)
        """)

        # v0.31.0: Trade history table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS trades (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL DEFAULT '1h',
                direction TEXT NOT NULL,
                entry_price REAL NOT NULL,
                exit_price REAL,
                entry_time TEXT,
                exit_time TEXT,
                size REAL DEFAULT 0,
                pnl REAL DEFAULT 0,
                pnl_pct REAL DEFAULT 0,
                confidence REAL DEFAULT 0,
                exit_reason TEXT DEFAULT '',
                regime TEXT DEFAULT '',
                leverage INTEGER DEFAULT 1,
                kelly_fraction REAL DEFAULT 0,
                position_size_pct REAL DEFAULT 0,
                sl_price REAL,
                tp_price REAL,
                matched_pattern TEXT,
                node_id TEXT DEFAULT '',
                session_id TEXT DEFAULT '',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_trades_symbol
            ON trades(symbol, timeframe, created_at DESC)
        """)

        # v0.31.0: Validation results table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS validations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL DEFAULT '1h',
                verdict TEXT NOT NULL,
                win_rate REAL DEFAULT 0,
                profit_factor REAL DEFAULT 0,
                risk_of_ruin REAL DEFAULT 0,
                p95_drawdown REAL DEFAULT 0,
                total_trades INTEGER DEFAULT 0,
                backtest_pnl_pct REAL DEFAULT 0,
                mc_probability_profit REAL DEFAULT 0,
                mc_verdict TEXT DEFAULT '',
                details TEXT DEFAULT '{}',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_validations_symbol
            ON validations(symbol, timeframe, created_at DESC)
        """)

        self._ensure_conn().commit()

    # === Asset Management ===

    def register_asset(self, symbol: str, asset_class: str) -> None:
        """Register or update an asset in the database."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO assets (symbol, asset_class, weight_profile, first_seen, last_updated)
               VALUES (?, ?, ?, datetime('now'), datetime('now'))
               ON CONFLICT(symbol) DO UPDATE SET
                   asset_class=excluded.asset_class,
                   last_updated=datetime('now')""",
            (symbol, asset_class, self._infer_weight_profile(asset_class)),
        )
        self._ensure_conn().commit()

    def get_assets(self) -> list[dict]:
        """Get all tracked assets with metadata."""
        cursor = self._ensure_conn().cursor()
        cursor.execute("""
            SELECT a.symbol, a.asset_class, a.weight_profile,
                   a.first_seen, a.last_updated, a.candle_count
            FROM assets a
            ORDER BY a.symbol
        """)
        columns = ["symbol", "asset_class", "weight_profile", "first_seen", "last_updated", "candle_count"]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    @staticmethod
    def _infer_weight_profile(asset_class: str) -> str:
        """Map asset class to weight profile name."""
        profile_map = {
            "blue_chip": "blue_chip",
            "large_cap": "default",
            "mid_cap": "default",
            "defi": "default",
            "meme": "meme",
            "new_launch": "new_launch",
        }
        return profile_map.get(asset_class, "default")

    # === OHLCV Data ===

    def save_ohlcv(self, symbol: str, timeframe: str, df: pd.DataFrame) -> int:
        """
        Save OHLCV candle data to the database.

        Uses INSERT OR IGNORE to avoid duplicates.

        Args:
            symbol: Trading pair (e.g., 'BTC/USDT')
            timeframe: Candle timeframe (e.g., '1h')
            df: DataFrame with columns: open, high, low, close, volume
                Index should be DatetimeIndex or have a 'timestamp' column.

        Returns:
            Number of new candles inserted.
        """
        if df.empty:
            return 0

        # Prepare data
        rows = []
        for idx, row in df.iterrows():
            # Handle both DatetimeIndex and timestamp column
            if hasattr(idx, "value"):
                # pandas DatetimeIndex → unix timestamp in ms
                ts = int(idx.value / 1_000_000)
            elif "timestamp" in df.columns:
                ts = int(row["timestamp"])
            else:
                ts = int(idx)

            rows.append((
                symbol,
                timeframe,
                ts,
                float(row["open"]),
                float(row["high"]),
                float(row["low"]),
                float(row["close"]),
                float(row["volume"]),
            ))

        cursor = self._ensure_conn().cursor()
        cursor.executemany(
            """INSERT OR IGNORE INTO ohlcv
               (symbol, timeframe, timestamp, open, high, low, close, volume)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            rows,
        )
        inserted = cursor.rowcount

        # Update asset candle count
        cursor.execute(
            "UPDATE assets SET candle_count = (SELECT COUNT(*) FROM ohlcv WHERE symbol = ?), last_updated = datetime('now') WHERE symbol = ?",
            (symbol, symbol),
        )

        self._ensure_conn().commit()
        return inserted

    def load_ohlcv(self, symbol: str, timeframe: str) -> pd.DataFrame:
        """
        Load OHLCV data for a symbol and timeframe.

        Returns:
            DataFrame with DatetimeIndex and columns: open, high, low, close, volume
        """
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """SELECT timestamp, open, high, low, close, volume
               FROM ohlcv
               WHERE symbol = ? AND timeframe = ?
               ORDER BY timestamp ASC""",
            (symbol, timeframe),
        )
        rows = cursor.fetchall()

        if not rows:
            return pd.DataFrame()

        df = pd.DataFrame(rows, columns=["timestamp", "open", "high", "low", "close", "volume"])
        df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")
        df = df.set_index("timestamp")
        return df

    def get_candle_count(self, symbol: str, timeframe: str) -> int:
        """Get the number of stored candles for a symbol/timeframe."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            "SELECT COUNT(*) FROM ohlcv WHERE symbol = ? AND timeframe = ?",
            (symbol, timeframe),
        )
        return cursor.fetchone()[0]

    def get_last_timestamp(self, symbol: str, timeframe: str) -> Optional[int]:
        """Get the last candle timestamp for incremental fetching."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            "SELECT MAX(timestamp) FROM ohlcv WHERE symbol = ? AND timeframe = ?",
            (symbol, timeframe),
        )
        result = cursor.fetchone()[0]
        return result

    # === Trie Persistence ===

    def save_trie(self, symbol: str, level: str, trie: PPMTTrie) -> None:
        """
        Save a serialized Trie to the database.

        Args:
            symbol: Trading pair
            level: Trie level ('n1', 'n2', 'n3', 'n4')
            trie: PPMTTrie instance to serialize
        """
        data = json.dumps(trie.to_dict())
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO tries (symbol, level, data, updated_at)
               VALUES (?, ?, ?, datetime('now'))
               ON CONFLICT(symbol, level) DO UPDATE SET
                   data=excluded.data,
                   updated_at=datetime('now')""",
            (symbol, level, data),
        )
        self._ensure_conn().commit()

    def load_trie(self, symbol: str, level: str) -> Optional[PPMTTrie]:
        """
        Load a serialized Trie from the database.

        Args:
            symbol: Trading pair
            level: Trie level ('n1', 'n2', 'n3', 'n4')

        Returns:
            PPMTTrie instance or None if not found.
        """
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            "SELECT data FROM tries WHERE symbol = ? AND level = ?",
            (symbol, level),
        )
        row = cursor.fetchone()
        if row is None:
            return None

        try:
            data = json.loads(row[0])
            return PPMTTrie.from_dict(data)
        except (json.JSONDecodeError, KeyError):
            return None

    def load_all_tries(self, symbol: str) -> dict[str, Optional[PPMTTrie]]:
        """
        Load all 4 trie levels for a symbol.

        v0.10.0: Convenience method for PaperTrader 4-level integration.

        Args:
            symbol: Trading pair

        Returns:
            Dict with keys 'n1', 'n2', 'n3', 'n4' mapping to PPMTTrie or None.
        """
        return {
            "n1": self.load_trie(symbol, "n1"),
            "n2": self.load_trie(symbol, "n2"),
            "n3": self.load_trie(symbol, "n3"),
            "n4": self.load_trie(symbol, "n4"),
        }

    # === Engine State ===

    def save_engine_state(self, symbol: str, state: dict) -> None:
        """Save engine state (weights, stats) for persistence."""
        data = json.dumps(state, default=str)
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO engine_states (symbol, data, updated_at)
               VALUES (?, ?, datetime('now'))
               ON CONFLICT(symbol) DO UPDATE SET
                   data=excluded.data,
                   updated_at=datetime('now')""",
            (symbol, data),
        )
        self._ensure_conn().commit()

    def load_engine_state(self, symbol: str) -> Optional[dict]:
        """Load engine state for a symbol."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            "SELECT data FROM engine_states WHERE symbol = ?",
            (symbol,),
        )
        row = cursor.fetchone()
        if row is None:
            return None

        try:
            return json.loads(row[0])
        except json.JSONDecodeError:
            return None

    # === Signal History ===

    def save_signal(self, signal_dict: dict) -> None:
        """Save a signal to the history log."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO signals
               (symbol, signal_type, confidence, quality_score, sizing_multiplier,
                entry_price, sl_price, tp_price, expected_move_pct, win_rate,
                remaining_candles, matched_pattern, predicted_path, timestamp)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                signal_dict.get("symbol", ""),
                signal_dict.get("signal_type", ""),
                signal_dict.get("confidence"),
                signal_dict.get("quality_score"),
                signal_dict.get("sizing_multiplier"),
                signal_dict.get("entry_price"),
                signal_dict.get("sl_price"),
                signal_dict.get("tp_price"),
                signal_dict.get("expected_move_pct"),
                signal_dict.get("win_rate"),
                signal_dict.get("remaining_candles"),
                json.dumps(signal_dict.get("matched_pattern", [])),
                json.dumps(signal_dict.get("predicted_path", [])),
                signal_dict.get("timestamp", 0),
            ),
        )
        self._ensure_conn().commit()

    def get_signals(
        self,
        symbol: str,
        limit: int = 100,
        signal_type: Optional[str] = None,
    ) -> list[dict]:
        """Get historical signals for a symbol."""
        cursor = self._ensure_conn().cursor()

        if signal_type:
            cursor.execute(
                """SELECT * FROM signals
                   WHERE symbol = ? AND signal_type = ?
                   ORDER BY timestamp DESC LIMIT ?""",
                (symbol, signal_type, limit),
            )
        else:
            cursor.execute(
                """SELECT * FROM signals
                   WHERE symbol = ?
                   ORDER BY timestamp DESC LIMIT ?""",
                (symbol, limit),
            )

        columns = [desc[0] for desc in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    # === Lifecycle ===

    def close(self) -> None:
        """Close the database connection."""
        if self.conn:
            self.conn.close()
            self.conn = None

    def __del__(self):
        self.close()

    # === Trade History (v0.31.0) ===

    def save_trade(self, trade_dict: dict) -> int:
        """Save a closed trade to the history log.

        Args:
            trade_dict: Dict with trade fields (symbol, direction, entry_price, etc.)

        Returns:
            Row ID of the inserted trade.
        """
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO trades
               (symbol, timeframe, direction, entry_price, exit_price,
                entry_time, exit_time, size, pnl, pnl_pct,
                confidence, exit_reason, regime, leverage,
                kelly_fraction, position_size_pct, sl_price, tp_price,
                matched_pattern, node_id, session_id)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                trade_dict.get("symbol", ""),
                trade_dict.get("timeframe", "1h"),
                trade_dict.get("direction", ""),
                trade_dict.get("entry_price", 0),
                trade_dict.get("exit_price", 0),
                trade_dict.get("entry_time", ""),
                trade_dict.get("exit_time", ""),
                trade_dict.get("size", 0),
                trade_dict.get("pnl", 0),
                trade_dict.get("pnl_pct", 0),
                trade_dict.get("confidence", 0),
                trade_dict.get("exit_reason", ""),
                trade_dict.get("regime", ""),
                trade_dict.get("leverage", 1),
                trade_dict.get("kelly_fraction", 0),
                trade_dict.get("position_size_pct", 0),
                trade_dict.get("sl_price"),
                trade_dict.get("tp_price"),
                json.dumps(trade_dict.get("matched_pattern", [])),
                trade_dict.get("node_id", ""),
                trade_dict.get("session_id", ""),
            ),
        )
        self._ensure_conn().commit()
        return cursor.lastrowid

    def get_trades(
        self,
        symbol: Optional[str] = None,
        timeframe: Optional[str] = None,
        limit: int = 100,
        node_id: Optional[str] = None,
    ) -> list[dict]:
        """Get closed trade history, most recent first.

        Args:
            symbol: Filter by symbol (optional)
            timeframe: Filter by timeframe (optional)
            limit: Max trades to return
            node_id: Filter by node ID (optional)
        """
        cursor = self._ensure_conn().cursor()
        conditions = []
        params = []

        if symbol:
            conditions.append("symbol = ?")
            params.append(symbol)
        if timeframe:
            conditions.append("timeframe = ?")
            params.append(timeframe)
        if node_id:
            conditions.append("node_id = ?")
            params.append(node_id)

        where = f"WHERE {' AND '.join(conditions)}" if conditions else ""
        params.append(limit)

        cursor.execute(
            f"""SELECT * FROM trades {where}
                ORDER BY created_at DESC LIMIT ?""",
            params,
        )
        columns = [desc[0] for desc in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    def get_trade_summary(self, symbol: Optional[str] = None) -> dict:
        """Get aggregate trade statistics.

        Returns total trades, win rate, P&L, etc.
        """
        cursor = self._ensure_conn().cursor()
        condition = "WHERE symbol = ?" if symbol else ""
        params = [symbol] if symbol else []

        cursor.execute(
            f"""SELECT COUNT(*) as total_trades,
                   SUM(CASE WHEN pnl_pct > 0 THEN 1 ELSE 0 END) as winning_trades,
                   SUM(CASE WHEN pnl_pct <= 0 THEN 1 ELSE 0 END) as losing_trades,
                   COALESCE(SUM(pnl), 0) as total_pnl,
                   COALESCE(AVG(pnl_pct), 0) as avg_pnl_pct,
                   COALESCE(MAX(pnl_pct), 0) as best_trade_pct,
                   COALESCE(MIN(pnl_pct), 0) as worst_trade_pct,
                   COALESCE(SUM(CASE WHEN pnl_pct > 0 THEN pnl_pct ELSE 0 END), 0) as gross_profit,
                   COALESCE(SUM(CASE WHEN pnl_pct < 0 THEN ABS(pnl_pct) ELSE 0 END), 0) as gross_loss
               FROM trades {condition}""",
            params,
        )
        row = cursor.fetchone()
        if row is None:
            return {"total_trades": 0}

        total = row[0] or 0
        wins = row[1] or 0
        gross_profit = row[7] or 0
        gross_loss = row[8] or 0.01

        return {
            "total_trades": total,
            "winning_trades": wins,
            "losing_trades": row[2] or 0,
            "win_rate": wins / total if total > 0 else 0,
            "total_pnl": row[3] or 0,
            "avg_pnl_pct": row[4] or 0,
            "best_trade_pct": row[5] or 0,
            "worst_trade_pct": row[6] or 0,
            "profit_factor": gross_profit / gross_loss if gross_loss > 0 else 0,
        }

    def clear_trades(self, symbol: Optional[str] = None, older_than_days: int = 0) -> int:
        """Delete trade history rows.

        v0.37.0: Added so users can clear stale/backtest trades that pollute
        the dashboard's Trade History panel (e.g. 434 fake BTC trades at
        $38,452 from a previous backtest, shown while trading XLM/OP/ICP).

        Args:
            symbol: If provided, only delete trades for this symbol.
                    If None, delete ALL trades (use with caution).
            older_than_days: If >0, only delete trades older than N days
                             (based on created_at). 0 = delete all matching.

        Returns:
            Number of rows deleted.
        """
        cursor = self._ensure_conn().cursor()
        conditions = []
        params: list = []

        if symbol:
            conditions.append("symbol = ?")
            params.append(symbol)
        if older_than_days > 0:
            conditions.append(
                "created_at < datetime('now', ?)"
            )
            params.append(f"-{older_than_days} days")

        where = f"WHERE {' AND '.join(conditions)}" if conditions else ""

        cursor.execute(f"DELETE FROM trades {where}", params)
        deleted = cursor.rowcount
        self._ensure_conn().commit()
        return deleted

    def clear_signals(self, symbol: Optional[str] = None, older_than_days: int = 0) -> int:
        """Delete signal history rows.

        v0.37.0: Companion to clear_trades() for clearing stale signals.

        Args:
            symbol: If provided, only delete signals for this symbol.
            older_than_days: If >0, only delete signals older than N days.

        Returns:
            Number of rows deleted.
        """
        cursor = self._ensure_conn().cursor()
        conditions = []
        params: list = []

        if symbol:
            conditions.append("symbol = ?")
            params.append(symbol)
        if older_than_days > 0:
            conditions.append(
                "created_at < datetime('now', ?)"
            )
            params.append(f"-{older_than_days} days")

        where = f"WHERE {' AND '.join(conditions)}" if conditions else ""

        cursor.execute(f"DELETE FROM signals {where}", params)
        deleted = cursor.rowcount
        self._ensure_conn().commit()
        return deleted

    # === Validation Results (v0.31.0) ===

    def save_validation(self, val_dict: dict) -> int:
        """Save a validation result."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO validations
               (symbol, timeframe, verdict, win_rate, profit_factor,
                risk_of_ruin, p95_drawdown, total_trades, backtest_pnl_pct,
                mc_probability_profit, mc_verdict, details)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                val_dict.get("symbol", ""),
                val_dict.get("timeframe", "1h"),
                val_dict.get("verdict", "UNKNOWN"),
                val_dict.get("win_rate", 0),
                val_dict.get("profit_factor", 0),
                val_dict.get("risk_of_ruin", 0),
                val_dict.get("p95_drawdown", 0),
                val_dict.get("total_trades", 0),
                val_dict.get("backtest_pnl_pct", 0),
                val_dict.get("mc_probability_profit", 0),
                val_dict.get("mc_verdict", ""),
                json.dumps(val_dict.get("details", {})),
            ),
        )
        self._ensure_conn().commit()
        return cursor.lastrowid

    def get_latest_validation(self, symbol: str, timeframe: str = "1h") -> Optional[dict]:
        """Get the most recent validation result for a symbol/timeframe."""
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """SELECT * FROM validations
               WHERE symbol = ? AND timeframe = ?
               ORDER BY created_at DESC LIMIT 1""",
            (symbol, timeframe),
        )
        row = cursor.fetchone()
        if row is None:
            return None
        columns = [desc[0] for desc in cursor.description]
        return dict(zip(columns, row))

    # === TokenProfile Persistence ===

    def save_token_profile(self, symbol: str, timeframe: str, profile_dict: dict) -> None:
        """
        Save a calibrated TokenProfile to the database.

        v0.11.0: Persists calibrated α/W and all profile parameters so the next
        run doesn't need to re-calibrate from scratch. The profile is stored
        in the engine_states table with a compound key 'symbol:timeframe:profile'.

        Args:
            symbol: Trading pair (e.g., 'BTC/USDT')
            timeframe: Candle timeframe (e.g., '1h')
            profile_dict: Serialized TokenProfile (from TokenProfile.to_dict())
        """
        key = f"{symbol}:{timeframe}:profile"
        data = json.dumps(profile_dict, default=str)
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            """INSERT INTO engine_states (symbol, data, updated_at)
               VALUES (?, ?, datetime('now'))
               ON CONFLICT(symbol) DO UPDATE SET
                   data=excluded.data,
                   updated_at=datetime('now')""",
            (key, data),
        )
        self._ensure_conn().commit()

    def load_token_profile(self, symbol: str, timeframe: str) -> Optional[dict]:
        """
        Load a saved TokenProfile from the database.

        v0.11.0: Returns the serialized profile dict if a calibrated profile
        was previously saved, or None if no profile exists for this
        symbol+timeframe combination. The caller can use this to skip
        calibration and go straight to trading.

        Args:
            symbol: Trading pair (e.g., 'BTC/USDT')
            timeframe: Candle timeframe (e.g., '1h')

        Returns:
            Dict with TokenProfile fields, or None if not found.
        """
        key = f"{symbol}:{timeframe}:profile"
        cursor = self._ensure_conn().cursor()
        cursor.execute(
            "SELECT data FROM engine_states WHERE symbol = ?",
            (key,),
        )
        row = cursor.fetchone()
        if row is None:
            return None

        try:
            return json.loads(row[0])
        except json.JSONDecodeError:
            return None
