#!/usr/bin/env bash
# ============================================================================
# PPMT Config Cleanup — v0.40.24-paper-cleanup
#
# Limpia y normaliza la configuración del usuario antes de arrancar
# `ppmt terminal` para paper trading 24-48h.
#
# Qué hace:
#   1. Backup automático con timestamp de config.yaml y groups_config.json
#   2. Reescribe config.yaml con secciones saneadas (sax + risk + signal)
#      preservando alphabet_size del usuario (default 5).
#   3. Reescribe groups_config.json con grupo único `paper_v1` (25 tokens
#      líquidos sanos con ratio 0.38-0.55 y >500 patterns en verify_all.sh).
#   4. Verifica que los archivos quedaron bien formados.
#
# Uso:
#   bash scripts/cleanup_config.sh
#
# Para rollback:
#   cp ~/.ppmt/config.yaml.bak-<timestamp> ~/.ppmt/config.yaml
#   cp ~/.ppmt/groups_config.json.bak-<timestamp> ~/.ppmt/groups_config.json
#
# Trazabilidad: ver TRAZABILIDAD.md entrada v0.40.24-paper-cleanup
# ============================================================================

set -euo pipefail

CONFIG_DIR="${HOME}/.ppmt"
CONFIG_FILE="${CONFIG_DIR}/config.yaml"
GROUPS_FILE="${CONFIG_DIR}/groups_config.json"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

echo "=== PPMT Config Cleanup (v0.40.24-paper-cleanup) ==="
echo "Timestamp: ${TIMESTAMP}"
echo ""

# ----------------------------------------------------------------------------
# 0. Validar que existe el directorio
# ----------------------------------------------------------------------------
if [[ ! -d "${CONFIG_DIR}" ]]; then
    echo "ERROR: No existe ${CONFIG_DIR}. Corré 'ppmt init' primero."
    exit 1
fi

# ----------------------------------------------------------------------------
# 1. Backup automático
# ----------------------------------------------------------------------------
echo "=== 1. Backup automático ==="

if [[ -f "${CONFIG_FILE}" ]]; then
    BACKUP_CFG="${CONFIG_FILE}.bak-${TIMESTAMP}"
    cp "${CONFIG_FILE}" "${BACKUP_CFG}"
    echo "  ✓ config.yaml → ${BACKUP_CFG}"
else
    echo "  - config.yaml no existe, se creará nuevo"
    BACKUP_CFG=""
fi

if [[ -f "${GROUPS_FILE}" ]]; then
    BACKUP_GRP="${GROUPS_FILE}.bak-${TIMESTAMP}"
    cp "${GROUPS_FILE}" "${BACKUP_GRP}"
    echo "  ✓ groups_config.json → ${BACKUP_GRP}"
else
    echo "  - groups_config.json no existe, se creará nuevo"
    BACKUP_GRP=""
fi
echo ""

# ----------------------------------------------------------------------------
# 2. Reescribir config.yaml
# ----------------------------------------------------------------------------
echo "=== 2. Reescribiendo config.yaml ==="

# Preservar alphabet_size del usuario si existe, sino usar 5
ALPHA=5
if [[ -f "${BACKUP_CFG}" ]]; then
    EXISTING_ALPHA=$(python3 -c "
import yaml
try:
    with open('${BACKUP_CFG}') as f:
        c = yaml.safe_load(f) or {}
    print(c.get('sax', {}).get('alphabet_size', 5))
except Exception:
    print(5)
" 2>/dev/null || echo 5)
    ALPHA="${EXISTING_ALPHA}"
fi
echo "  alphabet_size preservado: ${ALPHA}"

cat > "${CONFIG_FILE}" << YAML
# PPMT Configuration — v0.40.24-paper-cleanup
# Generated by scripts/cleanup_config.sh on ${TIMESTAMP}
# Backup: ${BACKUP_CFG}

# SAX Symbolization
sax:
  alphabet_size: ${ALPHA}     # Preservado del config anterior del usuario
  window_size: 10
  strategy: ohlcv

# Timeframes activos — el usuario va a operar principalmente en 1m y 5m,
# pero el motor debe soportar hasta 1h para análisis multi-TF.
timeframes:
  - 1m
  - 5m
  - 15m
  - 30m
  - 1h

# Build settings
build:
  forward_window: 5
  won_rr_threshold: 1.5
  pattern_length: 5

# Risk Management — CRÍTICO para paper trading
# Sin estos, el motor usa defaults internos que no podés tunear.
risk:
  max_position_size_pct: 0.02   # 2% del capital por trade
  max_daily_loss_pct: 0.05      # 5% pérdida máxima diaria
  max_drawdown_pct: 0.15        # 15% drawdown máximo
  min_risk_reward: 1.5          # R:R mínimo
  max_open_positions: 5

# Signal Generation
signal:
  min_confidence: 0.60          # Confianza mínima para generar señal
  unknown_block_exit: true      # Exit on unknown block
  trailing_stop_activation: 0.03   # 3% profit activa trailing
  trailing_stop_distance: 0.015    # 1.5% distancia trailing

# Logging
logging:
  level: INFO
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
YAML

echo "  ✓ ${CONFIG_FILE} escrito"
echo ""

# ----------------------------------------------------------------------------
# 3. Reescribir groups_config.json con paper_v1
# ----------------------------------------------------------------------------
echo "=== 3. Reescribiendo groups_config.json ==="

cat > "${GROUPS_FILE}" << 'JSON'
{
  "_comment": "PPMT Custom Token Groups — v0.40.24-paper-cleanup. Grupo único paper_v1 con 25 tokens líquidos sanos (ratio 0.38-0.55, >500 patterns en verify_all.sh).",
  "_generated_by": "scripts/cleanup_config.sh",
  "_backup_note": "Grupos anteriores preservados en .bak-<timestamp>",

  "paper_v1": {
    "label": "Paper v1 — 25 tokens saneados",
    "description": "Universo limpio para paper trading 24-48h. Todos los tokens tienen >500 patterns y ratio wins/count entre 0.38 y 0.55 en verify_all.sh v0.40.24.",
    "bases": [
      "BTC",
      "ETH",
      "SOL",
      "BNB",
      "XRP",
      "ADA",
      "AVAX",
      "DOT",
      "LINK",
      "LTC",
      "ATOM",
      "NEAR",
      "APT",
      "ARB",
      "OP",
      "INJ",
      "SUI",
      "TIA",
      "SEI",
      "TON",
      "PEPE",
      "SHIB",
      "DOGE",
      "WIF",
      "FLOKI"
    ]
  }
}
JSON

echo "  ✓ ${GROUPS_FILE} escrito"
echo ""

# ----------------------------------------------------------------------------
# 4. Verificar que quedaron bien formados
# ----------------------------------------------------------------------------
echo "=== 4. Verificación de integridad ==="

if python3 -c "import yaml; yaml.safe_load(open('${CONFIG_FILE}'))" 2>/dev/null; then
    echo "  ✓ config.yaml es YAML válido"
else
    echo "  ✗ ERROR: config.yaml no es YAML válido"
    exit 1
fi

if python3 -c "import json; json.load(open('${GROUPS_FILE}'))" 2>/dev/null; then
    echo "  ✓ groups_config.json es JSON válido"
else
    echo "  ✗ ERROR: groups_config.json no es JSON válido"
    exit 1
fi

# Contar tokens en paper_v1
COUNT=$(python3 -c "
import json
with open('${GROUPS_FILE}') as f:
    d = json.load(f)
print(len(d.get('paper_v1', {}).get('bases', [])))
")
echo "  ✓ paper_v1 tiene ${COUNT} tokens"

echo ""
echo "=== DONE ==="
echo ""
echo "Próximos pasos:"
echo "  1. Abrir ppmt terminal:   ppmt terminal"
echo "  2. En la UI, cargar el grupo 'paper_v1' en TOKEN GROUPS"
echo "  3. Setear VOLMIN=50M, VOLATMIN=1.5%, NO STABLE=ON"
echo "  4. Arrancar paper trading y monitorear 24-48h"
echo ""
echo "Para rollback:"
if [[ -n "${BACKUP_CFG}" ]]; then
    echo "  cp ${BACKUP_CFG} ${CONFIG_FILE}"
fi
if [[ -n "${BACKUP_GRP}" ]]; then
    echo "  cp ${BACKUP_GRP} ${GROUPS_FILE}"
fi
